name: zephyrcohu-spa

services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      TZ: 'Europe/Budapest'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
volumes:
  mysqldata: {}
